name: CI

on:
  push: 
    branches: [ main ]
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linter
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.0
          elixir-version: 1.16
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix credo --strict --ignore design.tagtodo
      - run: mix format --check-formatted

  test:
    strategy:
      matrix:
        version:
          - otp: 26.0
            elixir: 1.16
            os: ubuntu-latest
          - otp: 22.0
            elixir: 1.13
            # It's necessary to run on ubuntu 20.04 for OTP 20 - 23
            # See https://github.com/erlef/setup-beam
            os: ubuntu-20.04
    runs-on: ${{ matrix.version.os }}
    name: OTP ${{matrix.version.otp}} / Elixir ${{matrix.version.elixir}}
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.version.otp}}
          elixir-version: ${{matrix.version.elixir}}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix test
